wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_use_trajectory_view_api:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 3
      - 5
      4: 3.8.5
      5: 0.10.14
batch_mode:
  desc: null
  value: truncate_episodes
clip_actions:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.3
clip_rewards:
  desc: null
  value: null
collect_metrics_timeout:
  desc: null
  value: 180
compress_observations:
  desc: null
  value: false
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
custom_resources_per_worker:
  desc: null
  value: {}
date:
  desc: null
  value: 2021-03-14_01-21-37
eager_tracing:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.0
entropy_coeff_schedule:
  desc: null
  value: null
env:
  desc: null
  value: CarlaEnv
env_config:
  desc: null
  value:
    args: Namespace(client_gpu=3, client_timeout=999, host='127.0.0.1', n_vehicles=1,
      tm_port=9050, world_port=9000)
evaluation_config:
  desc: null
  value: {}
evaluation_interval:
  desc: null
  value: null
evaluation_num_episodes:
  desc: null
  value: 10
evaluation_num_workers:
  desc: null
  value: 0
experiment_id:
  desc: null
  value: cfef598a730e459fab79cc2f7175d707
exploration_config:
  desc: null
  value:
    type: StochasticSampling
explore:
  desc: null
  value: true
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
fake_sampler:
  desc: null
  value: false
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 0.99
grad_clip:
  desc: null
  value: null
horizon:
  desc: null
  value: null
hostname:
  desc: null
  value: lambda-quad
ignore_worker_failures:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
input:
  desc: null
  value: sampler
input_evaluation:
  desc: null
  value:
  - is
  - wis
kl_coeff:
  desc: null
  value: 0.2
kl_target:
  desc: null
  value: 0.01
lambda:
  desc: null
  value: 1.0
local_tf_session_args:
  desc: null
  value:
    inter_op_parallelism_threads: 8
    intra_op_parallelism_threads: 8
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
logger_config:
  desc: null
  value:
    wandb:
      api_key: 64820e399b4da86d50ba9f5931d435ceb2cc8846
      project: Carla_PPO_Single_Route
lr:
  desc: null
  value: 5.0e-05
lr_schedule:
  desc: null
  value: null
memory:
  desc: null
  value: 0
memory_per_worker:
  desc: null
  value: 0
metrics_smoothing_episodes:
  desc: null
  value: 100
min_iter_time_s:
  desc: null
  value: 0
model:
  desc: null
  value:
    _time_major: false
    attention_dim: 64
    attention_head_dim: 32
    attention_init_gru_gate_bias: 2.0
    attention_memory_inference: 50
    attention_memory_training: 50
    attention_num_heads: 1
    attention_num_transformer_units: 1
    attention_position_wise_mlp_dim: 32
    conv_activation: relu
    conv_filters: null
    custom_action_dist: null
    custom_model: my_model
    custom_model_config: {}
    custom_preprocessor: null
    dim: 84
    fcnet_activation: tanh
    fcnet_hiddens:
    - 256
    - 256
    framestack: true
    free_log_std: false
    grayscale: false
    lstm_cell_size: 256
    lstm_use_prev_action: false
    lstm_use_prev_action_reward: -1
    lstm_use_prev_reward: false
    max_seq_len: 20
    no_final_linear: false
    num_framestacks: auto
    post_fcnet_activation: relu
    post_fcnet_hiddens: []
    use_attention: false
    use_lstm: false
    vf_share_layers: false
    zero_mean: true
monitor:
  desc: null
  value: false
multiagent:
  desc: null
  value:
    count_steps_by: env_steps
    observation_fn: null
    policies: {}
    policies_to_train: null
    policy_mapping_fn: null
    replay_mode: independent
no_done_at_end:
  desc: null
  value: false
node_ip:
  desc: null
  value: 128.83.141.65
normalize_actions:
  desc: null
  value: false
num_cpus_for_driver:
  desc: null
  value: 1
num_cpus_per_worker:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 0
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 30
num_workers:
  desc: null
  value: 1
object_store_memory:
  desc: null
  value: 0
object_store_memory_per_worker:
  desc: null
  value: 0
observation_filter:
  desc: null
  value: NoFilter
optimizer:
  desc: null
  value: {}
output:
  desc: null
  value: null
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
pid:
  desc: null
  value: 18016
postprocess_inputs:
  desc: null
  value: false
preprocessor_pref:
  desc: null
  value: deepmind
record_env:
  desc: null
  value: false
remote_env_batch_wait_ms:
  desc: null
  value: 0
remote_worker_envs:
  desc: null
  value: false
render_env:
  desc: null
  value: false
replay_sequence_length:
  desc: null
  value: 1
rollout_fragment_length:
  desc: null
  value: 200
sample_async:
  desc: null
  value: false
sample_collector:
  desc: null
  value: <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>
seed:
  desc: null
  value: 1
sgd_minibatch_size:
  desc: null
  value: 128
shuffle_buffer_size:
  desc: null
  value: 0
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: true
soft_horizon:
  desc: null
  value: false
synchronize_filters:
  desc: null
  value: true
tf_session_args:
  desc: null
  value:
    allow_soft_placement: true
    device_count:
      CPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 2
    log_device_placement: false
timesteps_per_iteration:
  desc: null
  value: 0
train_batch_size:
  desc: null
  value: 4000
trial_id:
  desc: null
  value: a6ba6_00000
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 10.0
vf_loss_coeff:
  desc: null
  value: 1.0
vf_share_layers:
  desc: null
  value: -1
